env:
    - KAFKA_VERSION=0.8.1
    - KAFKA_VERSION=0.8.1.1
before_install:
    - curl https://archive.apache.org/dist/kafka/${KAFKA_VERSION}/kafka_2.8.0-${KAFKA_VERSION}.tgz | tar xvz
    - cd kafka_2.8.0-${KAFKA_VERSION}
    - bin/zookeeper-server-start.sh config/zookeeper.properties >/dev/null 2>&1 &
    - bin/kafka-server-start.sh config/server.properties >/dev/null 2>&1 &
    - cd -
install:
    - sudo apt-get install -qq ruby-dev gcc build-essential
    - sudo apt-get install -qq python-virtualenv
    - sudo apt-get install -qq rubygems gdebi
    - sudo apt-get install -qq nginx
    - sudo gem install bundler
    - sudo gem install fpm
    - cd flasfka-v0
    - sh pkgbuild.sh
    - sudo gdebi --n flasfka-v0*.deb
script:
    - echo "hello"
