env:
    - KAFKA_VERSION=0.8.1
    - KAFKA_VERSION=0.8.1.1
before_install:
    - curl https://archive.apache.org/dist/kafka/${KAFKA_VERSION}/kafka_2.8.0-${KAFKA_VERSION}.tgz | tar xvz
    - cd kafka_2.8.0-${KAFKA_VERSION}
    - bin/zookeeper-server-start.sh config/zookeeper.properties >/dev/null 2>&1 &
    - bin/kafka-server-start.sh config/server.properties >/dev/null 2>&1 &
    - cd -
install:
    - sudo apt-get install -qq ruby-dev gcc build-essential
    - sudo apt-get install -qq python-virtualenv
    - sudo apt-get install -qq rubygems gdebi-core
    - sudo apt-get install -qq nginx
    - rvmsudo gem install fpm
    - cd flasfka-v0
    - sh pkgbuild.sh
    - sudo gdebi -n flasfka-v0*.deb
    - sudo cp nginx.conf /etc/nginx/nginx.conf
    - sudo service nginx restart
script:
    - seq 1 200 | xargs -I % -n 1 curl -s -X POST --data-binary "test%" http://127.0.0.1/flasfka/v0/my-topic/
    - curl -s http://127.0.0.1/flasfka/v0/my-topic/
